language: python
python: 3.6
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/lektor/builds
    - $HOME/node_modules
    - $HOME/assets/dist
install:
  - "sudo apt-get update && sudo apt-get install nodejs yarn -y"
  - "pip install -U pip"
# Uncomment when new Lektor package is available
# - "pip install Lektor"
  - "pip install git+https://github.com/lektor/lektor#egg=Lektor"
script: "lektor build --no-prune"
deploy:
  - provider: script
    script: "lektor deploy develop"
    on:
       branch: develop
  - provider: script
    script: "lektor deploy production"
    on:
       branch: production